# linux command alias
alias cc='clear'

# kubectl alias
alias k='kubectl'
alias pods='kubectl get pods'
alias svc='kubectl get service'
alias deploy='kubectl get deployment'
alias nodes='kubectl get nodes'
alias ns='kubectl get namespace'
alias cm='kubectl get configmap'
alias secrets='kubectl get secret'
alias ing='kubectl get ingress'
alias pvc='kubectl get pvc'
alias pv='kubectl get pv'
alias jobs='kubectl get jobs'
alias cj='kubectl get cronjob'
alias events='kubectl get events'
alias rs='kubectl get replicaset'
alias sts='kubectl get statefulset'
alias ds='kubectl get daemonset'
alias dpods='kubectl describe pod'
alias dsvc='kubectl describe service'
alias ddeploy='kubectl describe deployment'
alias dnodes='kubectl describe node'
alias logs='kubectl logs -f'
alias exec='kubectl exec -it'
alias ctx='kubectl config current-context'
alias apply='kubectl apply -f'
alias delete='kubectl delete -f'
alias rr='kubectl rollout restart'
alias rst='kubectl rollout status'
alias top='kubectl top pods'
alias all='kubectl get all'
alias edit='kubectl edit'
