add_newline = false
command_timeout = 20

format = """$username$hostname$directory$character"""

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[git_status]
disabled = true

[package]
disabled = true

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
style = "blue bold"
format = "[@$hostname]($style) "

[directory]
style = "white bold"
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"
