views:
  v1/pods:
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - CONTROLLER:.metadata.ownerReferences[0].kind
      - READY
      - STATUS
      - RESTARTS
      - IMAGE:.spec.containers[0].image
      - IP
      - NODE